### ISSUE TITLE
how to easy deploy live torrent & backend server to heroku for make my own

### ISSUE THREAD

**Issue by todokku** [Davenchy/live-torrent#42]
Hi Davenchy ,
at the first , special thanks for your special live torrent stream serivice worked fine for me .
please tell me how to easy deploy live torrent & backend server to make my own at the easiest way to deploy it on heroku.
I know backend server have 'deploy to heroku button' but what changes needed for live-torrent to using backend server & what steps to run it ?
waiting for your response
finest regards
goodbye

**Comment by Davenchy** [comment]
Thank you for using live torrent and I am really sorry for taking too long to answer you.
For the current version of live torrent it doesn't need the backend server because it uses an old version of live-torrent-backend as a dependency package v1.1.0, I am working for new updates on live-torrent-backend so I can't update live torrent frontend at the moment till live-torrent-backend v2.0.0
I am really sorry for that

**Comment by Davenchy** [comment]
First of all, I am really sorry for taking too long to response.
Now you can use the heroku deploy button on live torrent project 94c1050d1ad753ccd807a0f21f1e8a04240956c1.
For the current version you don't need the backend server because the current version of live torrent uses live-torrent-backend as a dependency package, in the next major update you will need a separated backend server but for now just use the live torrent project itself.
I wish you a happy day.
goodbye
